"""Instruction prompts for the ingestion passes."""

INVENTORY_INSTRUCTIONS = (
    "You are cataloguing scanned exam materials. You will be shown every page of the "
    "materials for ONE exam, each preceded by a text label 'Page N:' giving its "
    "0-based global page index. Classify each page by role:\n"
    "- 'questions': pages containing exam questions to be answered\n"
    "- 'answer_key': pages listing correct answers (letters, values) without much prose\n"
    "- 'solutions': pages with worked solutions or model answers\n"
    "- 'rubric': pages with scoring guidelines / grading rubrics\n"
    "- 'cover': cover pages, instructions-only pages\n"
    "- 'other': anything else\n"
    "Also report the exam title, subject, and language (BCP-47 tag, e.g. 'zh-TW', 'en'), "
    "and last_question_number: the highest printed question number of the exam if the "
    "materials state it clearly (cover/instruction pages often print 'questions 1 to N'); "
    "use null if unsure. "
    "Classify EVERY page you are shown, using its labeled page index."
)

EXTRACT_INSTRUCTIONS = (
    "You are digitizing exam questions from scanned pages. Each page image is preceded "
    "by a text label 'Page N:' giving its 0-based global page index.\n"
    "Extract EVERY question that STARTS on these pages, in order, following these rules:\n"
    "- Transcribe question text VERBATIM as Markdown. Write math as LaTeX ($...$ inline, "
    "$$...$$ display). Preserve the original language exactly.\n"
    "- Tables become table blocks (header + rows of Markdown cells).\n"
    "- Every figure, diagram, graph, or picture needed to answer becomes a figure block "
    "with: the labeled page_index it appears on, a tight normalized bounding box "
    "(x0, y0, x1, y1; 0,0 = top-left of the page, 1,1 = bottom-right), and a detailed "
    "'alt' description of its content.\n"
    "- Question types: single_choice, multiple_choice, true_false, fill_in_blank, "
    "matching, short_answer (a few words/lines), essay (extended response), drawing "
    "(the answer is a drawing/graph/diagram), composite (a shared stimulus with "
    "sub-questions).\n"
    "- For choice questions, list options with their printed ids (A, B, C...). For "
    "fill-in-blank, create blanks 'b1', 'b2', ... in reading order. For matching, "
    "assign left ids 'L1'... and right ids 'R1'....\n"
    "- For composite questions put the shared stimulus in 'blocks' and each "
    "sub-question in 'children' with its printed label as 'number'.\n"
    "- Record the printed point value of each question if shown; use null if not.\n"
    "- Set continues_previous=true only if the first content on these pages is the "
    "continuation of a question that started on an earlier page (do not re-extract it; "
    "start with the first NEW question).\n"
    "- Skip page headers, footers, and page numbers."
)

ANSWERS_INSTRUCTIONS = (
    "You are digitizing the answer key / solutions / scoring rubric of an exam from "
    "scanned pages. Each page image is preceded by a text label 'Page N:' giving its "
    "0-based global page index. You are also given an index of the exam's questions "
    "(their printed numbers, types, points, and answer-field ids).\n"
    "For every question these pages provide information about, emit one entry:\n"
    "- question_number: the printed number EXACTLY as in the question index.\n"
    "- For choice questions: correct_options = the correct option id(s).\n"
    "- For true/false: true_false.\n"
    "- For fill-in-blank: blank_answers mapping each blank id from the index to ALL "
    "accepted answers (list variants: synonyms, alternate forms, units).\n"
    "- For matching: matching_pairs (left id -> right id from the index).\n"
    "- For open-ended questions: solution_text = the full model solution / reference "
    "answer as Markdown (math as LaTeX); rubric = scoring criteria with point levels "
    "if a rubric is given; judge_instructions = any grading guidance prose.\n"
    "- Figures inside solutions become solution_figures with page_index + normalized "
    "bbox + alt description.\n"
    "- If the exam's general instructions (often on a cover/instructions page) define "
    "per-option scoring for multiple-choice questions — each option judged "
    "independently, with the score determined by how many options were judged wrongly "
    "(e.g. 'all correct: full points; wrong on 1 option: 3/5 of the points; wrong on "
    "2: 1/5; otherwise 0') — copy that table into multi_choice_scoring.ratio_by_errors "
    "as ratios, e.g. [1.0, 0.6, 0.2]. Use null if no such rule is stated.\n"
    "Use null for fields that do not apply. Do not invent answers that are not in the "
    "materials."
)
